# Generated by Django 4.2.7 on 2023-11-04 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inner_text', models.CharField(max_length=100)),
                ('level_index', models.SmallIntegerField(db_index=True, default=0, unique=True)),
                ('column_index', models.SmallIntegerField(db_index=True, default=0)),
                ('hidden', models.BooleanField(default=False)),
                ('href', models.URLField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.menu', to_field='name')),
                ('parent_item', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.menuitem')),
            ],
        ),
    ]
