# Generated by Django 4.2.7 on 2023-11-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_menuitem_parent_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='level_index',
            field=models.SmallIntegerField(db_index=True, default=0),
        ),
    ]
